for _ in range(int(input())):
    print(' @@@   @@@ ')
    print('@   @ @   @')
    print('@    @    @')
    print('@         @')
    print(' @       @ ')
    print('  @     @  ')
    print('   @   @   ')
    print('    @ @    ')
    print('     @     ')