n = int(input())
print(' '.join([' @@@   @@@ ']*n))
print(' '.join(['@   @ @   @']*n))
print(' '.join(['@    @    @']*n))
print(' '.join(['@         @']*n))
print(' '.join([' @       @ ']*n))
print(' '.join(['  @     @  ']*n))
print(' '.join(['   @   @   ']*n))
print(' '.join(['    @ @    ']*n))
print(' '.join(['     @     ']*n))